version: '2.1'

services:
    tm1:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: bash -c "(python /elocal/src/udp_server.py -p 10000) & (tcpdump -i any -vvv -nn ip and udp)"
    tm2:
        build:
            context: docker
            dockerfile: Dockerfile-tema2
        privileged: true
        depends_on:
            - "tm1"
        volumes:
            - .:/elocal
        tty: true
        networks:
            - dmz
        command: python /elocal/src/udp_client.py --server tm1 --port 10000 --mesaj "Te vad din celalalt container"

networks:
    dmz: {}
